import Banner from "./Banner/Banner";
import Card from "./Card/Card";
import Carousel from "./Carousel/Carousel";
import Footer from "./Footer/Footer";
import Nav from "./Nav/nav";
import Form from "./FormPet/Form";
import Info from "./InfoPet/Info";
import Map from "./InfoPet/Map";
import DataPoint from "./InfoPet/PointDate";
export { Banner, Card, Carousel, Footer, Nav, Form, Info, Map, DataPoint };
